#!/bin/ksh

#APM00093000884-SEC-10.8.125.25 
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_acl_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_cel_$(date +%Y%m%d)
#ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_disk_$(date +%Y%m%d)
#ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_emailuser_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_fs_$(date +%Y%m%d)
#ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_inventory_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_license_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_pool_$(date +%Y%m%d)
#ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_replicate -list \" " > /data/storage_data/CELERRA/reports/depot/0884_nas_replicate_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_server_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_storage_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_version_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/0884_nas_cifs_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/0884_server_df_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/0884_server_dns_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_export ALL\" " >> /data/storage_data/CELERRA/reports/depot/0884_server_export_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/0884_server_ifconfig_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/0884_server_mountpoint_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/0884_server_nis_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/0884_server_param_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/0884_server_route_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/0884_server_usermapper_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/0884_server_version_$(date +%Y%m%d)
ssh -qn 10.8.125.25 " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/0884_server_viruschk_$(date +%Y%m%d)

#APM00083806333-edmonton-156.44.19.194
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_acl_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_cel_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_disk_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_emailuser_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_fs_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_inventory_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_license_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_pool_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_replicate -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_replicate_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_server_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_storage_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_version_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/6333_nas_cifs_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/6333_server_df_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/6333_server_dns_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/6333_server_export_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/6333_server_ifconfig_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/6333_server_mountpoint_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/6333_server_nis_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/6333_server_param_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/6333_server_route_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/6333_server_usermapper_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/6333_server_version_$(date +%Y%m%d)
ssh -qn 156.44.19.194 " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/6333_server_viruschk_$(date +%Y%m%d)

#APM00104001312-montreal-156.44.224.122 
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_acl_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_cel_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_disk_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_emailuser_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_fs_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_inventory_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_license_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_pool_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_replicate -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_replicate_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_server_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_storage_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_version_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/1312_nas_cifs_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/1312_server_df_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/1312_server_dns_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/1312_server_export_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/1312_server_ifconfig_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/1312_server_mountpoint_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/1312_server_nis_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/1312_server_param_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/1312_server_route_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/1312_server_usermapper_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/1312_server_version_$(date +%Y%m%d)
ssh -qn 156.44.224.122 " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/1312_server_viruschk_$(date +%Y%m%d)

#APM00072403528-mississuaga lubes-10.24.35.14 
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_acl_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_cel_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_disk_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_emailuser_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_fs_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_inventory_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_license_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_pool_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_replicate -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_replicate_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_server_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_storage_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_version_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/3528_nas_cifs_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/3528_server_df_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/3528_server_dns_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/3528_server_export_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/3528_server_ifconfig_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/3528_server_mountpoint_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/3528_server_nis_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/3528_server_param_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/3528_server_route_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/3528_server_usermapper_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/3528_server_version_$(date +%Y%m%d)
ssh -qn 10.24.35.14 " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/3528_server_viruschk_$(date +%Y%m%d)

#APM00102400907-st john-10.96.30.18
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_acl_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_cel_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_disk_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_emailuser_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_fs_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_inventory_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_license_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_pool_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_replicate -list \" " > /data/storage_data/CELERRA/reports/depot/0907_nas_replicate_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_server_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_storage_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_version_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/0907_nas_cifs_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/0907_server_df_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/0907_server_dns_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/0907_server_export_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/0907_server_ifconfig_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/0907_server_mountpoint_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/0907_server_nis_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/0907_server_param_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/0907_server_route_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/0907_server_usermapper_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/0907_server_version_$(date +%Y%m%d)
ssh -qn 10.96.30.18 " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/0907_server_viruschk_$(date +%Y%m%d)

#vnx1766-carefactor-10.146.96.175
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_acl_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_cel_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_disk_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_emailuser_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_fs_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_inventory_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_license_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_pool_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_replicate -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_replicate_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_server_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_storage_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_version_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/1766_nas_cifs_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/1766_server_df_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/1766_server_dns_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/1766_server_export_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/1766_server_ifconfig_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/1766_server_mountpoint_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/1766_server_nis_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/1766_server_param_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/1766_server_route_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/1766_server_usermapper_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/1766_server_version_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/1766_server_viruschk_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_usermapper ALL -Export -user /home/nasadmin/usermapper_backup_from_rogers/usermapper_passwd_$(date +%Y%m%d) \" "
scp  10.146.96.175:/home/nasadmin/work/usermapper_passwd_$(date +%Y%m%d) /data/storage_data/CELERRA/reports/depot/1766_server_mapper_passwd_$(date +%Y%m%d)
ssh -qn 10.146.96.175 " su - nasadmin -c \"/nas/bin/server_usermapper ALL -Export -group /home/nasadmin/usermapper_backup_from_rogers/usermapper_group_$(date +%Y%m%d) \" "
scp  10.146.96.175:/home/nasadmin/work/usermapper_group_$(date +%Y%m%d) /data/storage_data/CELERRA/reports/depot/1766_server_mapper_group_$(date +%Y%m%d)




#vnx1769-SEC-10.145.96.182
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_acl_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_cel_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_disk_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_emailuser_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_fs_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_inventory_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_license_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_pool_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_replicate -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_replicate_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_server_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_storage_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_version_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/1769_nas_cifs_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/1769_server_df_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/1769_server_dns_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/1769_server_export_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/1769_server_ifconfig_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/1769_server_mountpoint_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/1769_server_nis_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/1769_server_param_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/1769_server_route_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/1769_server_usermapper_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/1769_server_version_$(date +%Y%m%d)
ssh -qn 10.146.96.182 " su - nasadmin -c \"server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/1769_server_viruschk_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_usermapper ALL -Export -user /home/nasadmin/usermapper_temp/usermapper_passwd_$(date +%Y%m%d) \" "
scp  10.145.96.182:/home/nasadmin/usermapper_temp/usermapper_passwd_$(date +%Y%m%d) /data/storage_data/CELERRA/reports/depot/1769_server_mapper_passwd_$(date +%Y%m%d)
ssh -qn 10.145.96.182 " su - nasadmin -c \"/nas/bin/server_usermapper ALL -Export -group /home/nasadmin/usermapper_temp/usermapper_group_$(date +%Y%m%d) \" "
scp  10.145.96.182:/home/nasadmin/usermapper_temp/usermapper_group_$(date +%Y%m%d) /data/storage_data/CELERRA/reports/depot/1769_server_mapper_group_$(date +%Y%m%d)
ssh 10.145.96.182 "rm /home/nasadmin/usermapper_temp/usermapper_passwd_$(date +%Y%m%d)"
ssh 10.145.96.182 "rm /home/nasadmin/usermapper_temp/usermapper_group_$(date +%Y%m%d)"





#vnx3294-RUNCORN-10.65.139.15
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_acl_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_cel_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_disk_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_emailuser_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_fs_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_inventory_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_license_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_pool_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_replicate -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_replicate_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_server_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_storage_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_version_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/3294_nas_cifs_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/3294_server_df_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/3294_server_dns_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/3294_server_export_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/3294_server_ifconfig_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/3294_server_mountpoint_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/3294_server_nis_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/3294_server_param_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/3294_server_route_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/3294_server_usermapper_$(date +%Y%m%d)
ssh -qn 10.65.139.15 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/3294_server_version_$(date +%Y%m%d)
ssh -qn 10.65.139.15  " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/3294_server_viruschk_$(date +%Y%m%d)

#vnx9283-TORONTO-10.22.80.130
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_acl -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_acl_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_cel -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_cel_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_ckpt_schedule -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_ckpt_schedule_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_disk -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_disk_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_emailuser -info\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_emailuser_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_fs -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_fs_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_inventory -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_inventory_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_license -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_license_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_pool -size -all\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_pool_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_replicate -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_replicate_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_server -list -all\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_server_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_storage -list\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_storage_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/nas_version\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_version_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_cifs ALL\" " > /data/storage_data/CELERRA/reports/depot/9283_nas_cifs_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_df ALL\" " > /data/storage_data/CELERRA/reports/depot/9283_server_df_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_dns ALL\" " > /data/storage_data/CELERRA/reports/depot/9283_server_dns_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_export ALL\" " > /data/storage_data/CELERRA/reports/depot/9283_server_export_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_ifconfig ALL -all\" " > /data/storage_data/CELERRA/reports/depot/9283_server_ifconfig_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_mountpoint ALL -list\" " > /data/storage_data/CELERRA/reports/depot/9283_server_mountpoint_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_nis ALL -status\" " > /data/storage_data/CELERRA/reports/depot/9283_server_nis_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_param ALL -facility -all -list\" " > /data/storage_data/CELERRA/reports/depot/9283_server_param_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_route ALL -list\" " > /data/storage_data/CELERRA/reports/depot/9283_server_route_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_usermapper ALL\" " > /data/storage_data/CELERRA/reports/depot/9283_server_usermapper_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_version ALL\" " > /data/storage_data/CELERRA/reports/depot/9283_server_version_$(date +%Y%m%d)
ssh -qn 10.22.80.130 " su - nasadmin -c \"/nas/bin/server_viruschk ALL\" " > /data/storage_data/CELERRA/reports/depot/9283_server_viruschk_$(date +%Y%m%d)

mkdir /data/storage_data/CELERRA/reports/depot/$(date +%Y%m%d)
mv /data/storage_data/CELERRA/reports/depot/*_$(date +%Y%m%d) /data/storage_data/CELERRA/reports/depot/$(date +%Y%m%d)/.
